//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitOSA.WallReinforcer.Resources1P {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ElemMarkDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ElemMarkDescriptions() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RevitOSA.WallReinforcer.Resources1P.ElemMarkDescriptions", typeof(ElemMarkDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на балки;балок;Балка;Балки.
        /// </summary>
        public static string Бм {
            get {
                return ResourceManager.GetString("Бм", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на балки лестничной;балок лестничных;Балка лестничная;Балки лестничные.
        /// </summary>
        public static string Бмл {
            get {
                return ResourceManager.GetString("Бмл", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на блока шахты лифта;блоков шахты лифта;Блок шахты лифта;Блоки шахты лифта.
        /// </summary>
        public static string Бшл {
            get {
                return ResourceManager.GetString("Бшл", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на группы закладных деталей;групп закладных деталей;Группа закладных деталей; Группы закладных деталей.
        /// </summary>
        public static string ГЗД {
            get {
                return ResourceManager.GetString("ГЗД", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на диафрагмы;диафрагм;Диафрагма;Диафрагмы.
        /// </summary>
        public static string Дм {
            get {
                return ResourceManager.GetString("Дм", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на колонны;колонн;Колонна;Колонны.
        /// </summary>
        public static string К {
            get {
                return ResourceManager.GetString("К", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на каркаса обвязочной балки;каркасов обвязочных балкок;Каркас обвязочной балки;Каркасы обвязочных балкок.
        /// </summary>
        public static string Коб {
            get {
                return ResourceManager.GetString("Коб", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на каркаса поддерживающего;каркасов поддерживающих;Каркас поддерживающий;Каркасы поддерживающие.
        /// </summary>
        public static string Кп {
            get {
                return ResourceManager.GetString("Кп", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на каркаса пространственного балочного;каркасов пространственных балочных;Каркас пространственный балочный;Каркасы пространственные балочные.
        /// </summary>
        public static string КпБ {
            get {
                return ResourceManager.GetString("КпБ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на каркаса лестничного поддерживающего;каркасов лестничных поддерживающих;Каркас лестничный поддерживающий;Каркасы лестничные поддерживающие.
        /// </summary>
        public static string КпЛ {
            get {
                return ResourceManager.GetString("КпЛ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на каркаса пространственного плитного;каркасов пространственных плитных;Каркас пространственный плитный;Каркасы пространственные плитные.
        /// </summary>
        public static string КпП {
            get {
                return ResourceManager.GetString("КпП", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на каркаса поддерживающего ростверка ;каркасов поддерживающих ростверка;Каркас поддерживающий ростверка;Каркасы поддерживающие ростверка.
        /// </summary>
        public static string КпР {
            get {
                return ResourceManager.GetString("КпР", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на каркаса плоского;каркасов плоских;Каркас плоский;Каркасы плоские.
        /// </summary>
        public static string Кр {
            get {
                return ResourceManager.GetString("Кр", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на каркаса балочного;каркасов балочных;Каркас балочный;Каркасы балочные.
        /// </summary>
        public static string КрБ {
            get {
                return ResourceManager.GetString("КрБ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на каркас колонны;каркасов колонн;Каркас колонны;Каркасы колонн.
        /// </summary>
        public static string КрК {
            get {
                return ResourceManager.GetString("КрК", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на каркаса лестничного;каркасов лестничных;Каркас лестничный;Каркасы лестничные.
        /// </summary>
        public static string КрЛ {
            get {
                return ResourceManager.GetString("КрЛ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на каркаса ростверка;каркасов ростверка;Каркас ростверка;Каркасы ростверка.
        /// </summary>
        public static string КрР {
            get {
                return ResourceManager.GetString("КрР", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на лестничного марша;лестничных маршей;Лестничный марш;Лестничные марши.
        /// </summary>
        public static string Лм {
            get {
                return ResourceManager.GetString("Лм", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на пилоны;пилонов;Пилон;Пилоны.
        /// </summary>
        public static string П {
            get {
                return ResourceManager.GetString("П", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на плиты;плит;Плита;Плиты.
        /// </summary>
        public static string Пм {
            get {
                return ResourceManager.GetString("Пм", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на площадки;площадок;Площадка;Площадки.
        /// </summary>
        public static string Пмл {
            get {
                return ResourceManager.GetString("Пмл", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на плиты приямка; плит приямка; Плита прияка; Плиты приямка.
        /// </summary>
        public static string Пп {
            get {
                return ResourceManager.GetString("Пп", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на покрытия шахты лифта;покрытий шахты лифта;Покрытие шахты лифта;Покрытия шахты лифта.
        /// </summary>
        public static string Пшл {
            get {
                return ResourceManager.GetString("Пшл", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на раскосы;раскосов;Раскос;Раскосы.
        /// </summary>
        public static string Р {
            get {
                return ResourceManager.GetString("Р", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ростверка;ростверков;Ростверк;Ростверки.
        /// </summary>
        public static string Рм {
            get {
                return ResourceManager.GetString("Рм", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на сетки;сеток;Сетка;Сетки.
        /// </summary>
        public static string С {
            get {
                return ResourceManager.GetString("С", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на спуска в подвал;спусков в подвал;Спуск в подвал;Спуски в подвал.
        /// </summary>
        public static string СвП {
            get {
                return ResourceManager.GetString("СвП", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на стены;стен;Стена;Стены.
        /// </summary>
        public static string Стм {
            get {
                return ResourceManager.GetString("Стм", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на стены шахты лифта;стен шахты лифта;Стена шахты лифта;Стены шахты лифта.
        /// </summary>
        public static string Сшл {
            get {
                return ResourceManager.GetString("Сшл", resourceCulture);
            }
        }
    }
}
