//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitOSA.WallReinforcer.Resources1P {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReinforcementPartitionNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReinforcementPartitionNames() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RevitOSA.WallReinforcer.Resources1P.ReinforcementPartitionNames", typeof(ReinforcementPartitionNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 04_Выпуски.
        /// </summary>
        public static string reinfPartName_Anchors {
            get {
                return ResourceManager.GetString("reinfPartName_Anchors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 03_Каркасы.
        /// </summary>
        public static string reinfPartName_Cages {
            get {
                return ResourceManager.GetString("reinfPartName_Cages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 05_Фрагменты.
        /// </summary>
        public static string reinfPartName_DetailReinf {
            get {
                return ResourceManager.GetString("reinfPartName_DetailReinf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 01_Расположение_Горизонтальная_Внутри.
        /// </summary>
        public static string reinfPartName_HorizInside {
            get {
                return ResourceManager.GetString("reinfPartName_HorizInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 01_Расположение_Горизонтальная_Внутри_Доп.
        /// </summary>
        public static string reinfPartName_HorizInside_Additional {
            get {
                return ResourceManager.GetString("reinfPartName_HorizInside_Additional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 01_Расположение_Горизонтальная_Снаружи.
        /// </summary>
        public static string reinfPartName_HorizOutside {
            get {
                return ResourceManager.GetString("reinfPartName_HorizOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 01_Расположение_Горизонтальная_Снаружи_Доп.
        /// </summary>
        public static string reinfPartName_HorizOutside_Additional {
            get {
                return ResourceManager.GetString("reinfPartName_HorizOutside_Additional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 02_П-образные хомуты.
        /// </summary>
        public static string reinfPartName_PStirrups {
            get {
                return ResourceManager.GetString("reinfPartName_PStirrups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 06_Шпильки_Нечетный ряд.
        /// </summary>
        public static string reinfPartName_Studs_EvenRow {
            get {
                return ResourceManager.GetString("reinfPartName_Studs_EvenRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 06_Шпильки_Четный ряд.
        /// </summary>
        public static string reinfPartName_Studs_OddRow {
            get {
                return ResourceManager.GetString("reinfPartName_Studs_OddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 01_Расположение_Вертикальная_Угловая.
        /// </summary>
        public static string reinfPartName_VertCorner {
            get {
                return ResourceManager.GetString("reinfPartName_VertCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 01_Расположение_Вертикальная_Внутри.
        /// </summary>
        public static string reinfPartName_VertInside {
            get {
                return ResourceManager.GetString("reinfPartName_VertInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 01_Расположение_Вертикальная_Внутри_Доп.
        /// </summary>
        public static string reinfPartName_VertInside_Additional {
            get {
                return ResourceManager.GetString("reinfPartName_VertInside_Additional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 01_Расположение_Вертикальная_Снаружи.
        /// </summary>
        public static string reinfPartName_VertOutside {
            get {
                return ResourceManager.GetString("reinfPartName_VertOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 01_Расположение_Вертикальная_Снаружи_Доп.
        /// </summary>
        public static string reinfPartName_VertOutside_Additional {
            get {
                return ResourceManager.GetString("reinfPartName_VertOutside_Additional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 01_Расположение_X_Низ.
        /// </summary>
        public static string reinfPartName_XBottom {
            get {
                return ResourceManager.GetString("reinfPartName_XBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 01_Расположение_X_Верх.
        /// </summary>
        public static string reinfPartName_XTop {
            get {
                return ResourceManager.GetString("reinfPartName_XTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 01_Расположение_Y_Низ.
        /// </summary>
        public static string reinfPartName_YBottom {
            get {
                return ResourceManager.GetString("reinfPartName_YBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 01_Расположение_Y_Верх.
        /// </summary>
        public static string reinfPartName_YTop {
            get {
                return ResourceManager.GetString("reinfPartName_YTop", resourceCulture);
            }
        }
    }
}
