//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitOSA.WallReinforcer.Resources1P {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RevitParameters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RevitParameters() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RevitOSA.WallReinforcer.Resources1P.RevitParameters", typeof(RevitParameters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8d057bb3-6ccd-4655-9165-55526691fe3a.
        /// </summary>
        public static string p_Amount {
            get {
                return ResourceManager.GetString("p_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 9b679ab7-ea2e-49ce-90ab-0549d5aa36ff.
        /// </summary>
        public static string p_Dims_Diameter {
            get {
                return ResourceManager.GetString("p_Dims_Diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 6ca8be7d-c26e-4287-bef4-a95cbbccfe39.
        /// </summary>
        public static string p_Dims_Elevation {
            get {
                return ResourceManager.GetString("p_Dims_Elevation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на da753fe3-ecfa-465b-9a2c-02f55d0c2ff1.
        /// </summary>
        public static string p_Dims_Height {
            get {
                return ResourceManager.GetString("p_Dims_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 844a01e2-19fc-4dc5-baa0-a4bda30ef1f6.
        /// </summary>
        public static string p_Dims_InRunningMeters {
            get {
                return ResourceManager.GetString("p_Dims_InRunningMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 748a2515-4cc9-4b74-9a69-339a8d65a212.
        /// </summary>
        public static string p_Dims_Length {
            get {
                return ResourceManager.GetString("p_Dims_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 293f055d-6939-4611-87b7-9a50d0c1f50e.
        /// </summary>
        public static string p_Dims_Thickness {
            get {
                return ResourceManager.GetString("p_Dims_Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8f2e4f93-9472-4941-a65d-0ac468fd6a5d.
        /// </summary>
        public static string p_Dims_Width {
            get {
                return ResourceManager.GetString("p_Dims_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 9eabf56c-a6cd-4b5c-a9d0-e9223e19ea3f.
        /// </summary>
        public static string p_Identity_Level {
            get {
                return ResourceManager.GetString("p_Identity_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 7b011a82-6ead-45ee-a188-7a7721dfb452.
        /// </summary>
        public static string p_Identity_MainElement {
            get {
                return ResourceManager.GetString("p_Identity_MainElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на e6e0f5cd-3e26-485b-9342-23882b20eb43.
        /// </summary>
        public static string p_Identity_Name {
            get {
                return ResourceManager.GetString("p_Identity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8d2d9fad-1799-4428-8724-3354c4183462.
        /// </summary>
        public static string p_Identity_Number_OfPile {
            get {
                return ResourceManager.GetString("p_Identity_Number_OfPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c5cd7b89-b2f0-45c4-98ba-0323ed9b25f9.
        /// </summary>
        public static string p_Identity_Section {
            get {
                return ResourceManager.GetString("p_Identity_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 9c98831b-9450-412d-b072-7d69b39f4029.
        /// </summary>
        public static string p_Identity_SheetReference {
            get {
                return ResourceManager.GetString("p_Identity_SheetReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c78f0a7d-b68b-4d21-a247-1c8c6ced8bc5.
        /// </summary>
        public static string p_Identity_Zone {
            get {
                return ResourceManager.GetString("p_Identity_Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 476aa446-b9ab-4f3c-99ea-7d2740b0ed8b.
        /// </summary>
        public static string p_Mark_Complicate_Length1 {
            get {
                return ResourceManager.GetString("p_Mark_Complicate_Length1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2b1c2c3f-123d-4b25-8096-86b8bb920ce1.
        /// </summary>
        public static string p_Mark_Complicate_Length2 {
            get {
                return ResourceManager.GetString("p_Mark_Complicate_Length2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 810c026d-79ed-4f10-b45e-5db312ae43bb.
        /// </summary>
        public static string p_Mark_Complicate_Length3 {
            get {
                return ResourceManager.GetString("p_Mark_Complicate_Length3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3601a2b2-2cdc-4e35-bb35-1de1737c45a8.
        /// </summary>
        public static string p_Mark_Complicate_Text1 {
            get {
                return ResourceManager.GetString("p_Mark_Complicate_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на e6e4bdf9-cec1-4b4d-8a08-89aa2f668931.
        /// </summary>
        public static string p_Mark_Complicate_Text2 {
            get {
                return ResourceManager.GetString("p_Mark_Complicate_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5d369dfb-17a2-4ae2-a1a1-bdfc33ba7405.
        /// </summary>
        public static string p_Mark_Construction {
            get {
                return ResourceManager.GetString("p_Mark_Construction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 92ae0425-031b-40a9-8904-023f7389963b.
        /// </summary>
        public static string p_Mark_Item {
            get {
                return ResourceManager.GetString("p_Mark_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 01b0db9a-3ed0-4957-98c2-7bbaf81892cb.
        /// </summary>
        public static string p_Mark_Void {
            get {
                return ResourceManager.GetString("p_Mark_Void", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 32989501-0d17-4916-8777-da950841c6d7.
        /// </summary>
        public static string p_Mass {
            get {
                return ResourceManager.GetString("p_Mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8b5e61a2-b091-491c-8092-0b01a55d4f44.
        /// </summary>
        public static string p_Material {
            get {
                return ResourceManager.GetString("p_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b5ef18b4-453e-49bd-b26c-dfb3bd3ca79c.
        /// </summary>
        public static string p_Reinf_A {
            get {
                return ResourceManager.GetString("p_Reinf_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на bef64550-0992-4b59-a616-1acaa2e24065.
        /// </summary>
        public static string p_Reinf_B {
            get {
                return ResourceManager.GetString("p_Reinf_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 32a47c7f-e91d-4a8e-bf24-927cb679b4d1.
        /// </summary>
        public static string p_Reinf_Class {
            get {
                return ResourceManager.GetString("p_Reinf_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на dce379c0-5e32-4695-b16a-d76ef0100172.
        /// </summary>
        public static string p_Reinf_Prefix {
            get {
                return ResourceManager.GetString("p_Reinf_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4d1d1719-6bd9-4357-9378-a1d77871e0fd.
        /// </summary>
        public static string p_Reinf_V {
            get {
                return ResourceManager.GetString("p_Reinf_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b6e73342-b6cd-42c5-86c5-64b04b5b88de.
        /// </summary>
        public static string p_TitleBlock_SheetNumber {
            get {
                return ResourceManager.GetString("p_TitleBlock_SheetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 7f0c8590-53a2-4ddf-aaed-c70eb9b687bc.
        /// </summary>
        public static string p_TitleBlock_SheetSet {
            get {
                return ResourceManager.GetString("p_TitleBlock_SheetSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Класс бетона.
        /// </summary>
        public static string pp_BClass {
            get {
                return ResourceManager.GetString("pp_BClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Наименование контейнера.
        /// </summary>
        public static string pp_Container_Name {
            get {
                return ResourceManager.GetString("pp_Container_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Обозначение контейнера.
        /// </summary>
        public static string pp_Container_SheetReference {
            get {
                return ResourceManager.GetString("pp_Container_SheetReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Отделка потолка_Площадь.
        /// </summary>
        public static string pp_Decor_Ceiling_Area {
            get {
                return ResourceManager.GetString("pp_Decor_Ceiling_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Отделка пола_Площадь.
        /// </summary>
        public static string pp_Decor_Floor_Area {
            get {
                return ResourceManager.GetString("pp_Decor_Floor_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Отделка пола_Минимальная толщина.
        /// </summary>
        public static string pp_Decor_Floor_MinT {
            get {
                return ResourceManager.GetString("pp_Decor_Floor_MinT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Отделка стен_Площадь1.
        /// </summary>
        public static string pp_Decor_Wall_Area1 {
            get {
                return ResourceManager.GetString("pp_Decor_Wall_Area1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Отделка стен_Площадь2.
        /// </summary>
        public static string pp_Decor_Wall_Area2 {
            get {
                return ResourceManager.GetString("pp_Decor_Wall_Area2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Отделка стен_Площадь3.
        /// </summary>
        public static string pp_Decor_Wall_Area3 {
            get {
                return ResourceManager.GetString("pp_Decor_Wall_Area3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Отделка стен_Площадь4.
        /// </summary>
        public static string pp_Decor_Wall_Area4 {
            get {
                return ResourceManager.GetString("pp_Decor_Wall_Area4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Отделка стен_Площадь5.
        /// </summary>
        public static string pp_Decor_Wall_Area5 {
            get {
                return ResourceManager.GetString("pp_Decor_Wall_Area5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Отделка стен_Описание1.
        /// </summary>
        public static string pp_Decor_Wall_Description1 {
            get {
                return ResourceManager.GetString("pp_Decor_Wall_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Отделка стен_Описание2.
        /// </summary>
        public static string pp_Decor_Wall_Description2 {
            get {
                return ResourceManager.GetString("pp_Decor_Wall_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Отделка стен_Описание3.
        /// </summary>
        public static string pp_Decor_Wall_Description3 {
            get {
                return ResourceManager.GetString("pp_Decor_Wall_Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Отделка стен_Описание4.
        /// </summary>
        public static string pp_Decor_Wall_Description4 {
            get {
                return ResourceManager.GetString("pp_Decor_Wall_Description4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Отделка стен_Описание5.
        /// </summary>
        public static string pp_Decor_Wall_Description5 {
            get {
                return ResourceManager.GetString("pp_Decor_Wall_Description5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Отделка стен_Минимальная толщина.
        /// </summary>
        public static string pp_Decor_Wall_MinT {
            get {
                return ResourceManager.GetString("pp_Decor_Wall_MinT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Наименование.
        /// </summary>
        public static string pp_Name {
            get {
                return ResourceManager.GetString("pp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Номер столбца.
        /// </summary>
        public static string pp_Number_OfCol {
            get {
                return ResourceManager.GetString("pp_Number_OfCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Номер этажа.
        /// </summary>
        public static string pp_Number_OfLevel {
            get {
                return ResourceManager.GetString("pp_Number_OfLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Арм_Доп_Низ_Диаметр.
        /// </summary>
        public static string pp_Reinf_AddBottom_D {
            get {
                return ResourceManager.GetString("pp_Reinf_AddBottom_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Арм_Доп_Верх_Диаметр.
        /// </summary>
        public static string pp_Reinf_AddTop_D {
            get {
                return ResourceManager.GetString("pp_Reinf_AddTop_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Арм_Консоль.
        /// </summary>
        public static string pp_Reinf_AsCantilever {
            get {
                return ResourceManager.GetString("pp_Reinf_AsCantilever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Арм_Каркас_Диаметр.
        /// </summary>
        public static string pp_Reinf_Cage_D {
            get {
                return ResourceManager.GetString("pp_Reinf_Cage_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Арм_Торец_Диаметр.
        /// </summary>
        public static string pp_Reinf_Edge_D {
            get {
                return ResourceManager.GetString("pp_Reinf_Edge_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Арм_Max_Низ_Диаметр.
        /// </summary>
        public static string pp_Reinf_MaxBottom_D {
            get {
                return ResourceManager.GetString("pp_Reinf_MaxBottom_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Арм_Max_Верх_Диаметр.
        /// </summary>
        public static string pp_Reinf_MaxTop_D {
            get {
                return ResourceManager.GetString("pp_Reinf_MaxTop_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Арм_X_Диаметр.
        /// </summary>
        public static string pp_Reinf_X_D {
            get {
                return ResourceManager.GetString("pp_Reinf_X_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Арм_X_Количество.
        /// </summary>
        public static string pp_Reinf_X_N {
            get {
                return ResourceManager.GetString("pp_Reinf_X_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Арм_X_Шаг.
        /// </summary>
        public static string pp_Reinf_X_Step {
            get {
                return ResourceManager.GetString("pp_Reinf_X_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Арм_X_Низ_Диаметр.
        /// </summary>
        public static string pp_Reinf_XBottom_D {
            get {
                return ResourceManager.GetString("pp_Reinf_XBottom_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Арм_X_Верх_Диаметр.
        /// </summary>
        public static string pp_Reinf_XTop_D {
            get {
                return ResourceManager.GetString("pp_Reinf_XTop_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Арм_Y_Диаметр.
        /// </summary>
        public static string pp_Reinf_Y_D {
            get {
                return ResourceManager.GetString("pp_Reinf_Y_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Арм_Y_Количество.
        /// </summary>
        public static string pp_Reinf_Y_N {
            get {
                return ResourceManager.GetString("pp_Reinf_Y_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Арм_Y_Шаг.
        /// </summary>
        public static string pp_Reinf_Y_Step {
            get {
                return ResourceManager.GetString("pp_Reinf_Y_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Арм_Y_Низ_Диаметр.
        /// </summary>
        public static string pp_Reinf_YBottom_D {
            get {
                return ResourceManager.GetString("pp_Reinf_YBottom_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Арм_Y_Верх_Диаметр.
        /// </summary>
        public static string pp_Reinf_YTop_D {
            get {
                return ResourceManager.GetString("pp_Reinf_YTop_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Обозначение.
        /// </summary>
        public static string pp_SheetReference {
            get {
                return ResourceManager.GetString("pp_SheetReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1Пп_Эталон.
        /// </summary>
        public static string pp_StandartItem {
            get {
                return ResourceManager.GetString("pp_StandartItem", resourceCulture);
            }
        }
    }
}
