//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitOSA.WallReinforcer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.5.0.0")]
    public sealed partial class Annotations : global::System.Configuration.ApplicationSettingsBase {
        
        private static Annotations defaultInstance = ((Annotations)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Annotations())));
        
        public static Annotations Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double gridTail_l0 {
            get {
                return ((double)(this["gridTail_l0"]));
            }
            set {
                this["gridTail_l0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public double ciTagOffset_a0 {
            get {
                return ((double)(this["ciTagOffset_a0"]));
            }
            set {
                this["ciTagOffset_a0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220")]
        public double ciTagOffset_a1 {
            get {
                return ((double)(this["ciTagOffset_a1"]));
            }
            set {
                this["ciTagOffset_a1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double ciTagOffset_a2 {
            get {
                return ((double)(this["ciTagOffset_a2"]));
            }
            set {
                this["ciTagOffset_a2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int rebarBoundLineStyle_IntId {
            get {
                return ((int)(this["rebarBoundLineStyle_IntId"]));
            }
            set {
                this["rebarBoundLineStyle_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int rebarHiddenPattern_IntId {
            get {
                return ((int)(this["rebarHiddenPattern_IntId"]));
            }
            set {
                this["rebarHiddenPattern_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int cropLineType_IntId {
            get {
                return ((int)(this["cropLineType_IntId"]));
            }
            set {
                this["cropLineType_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ciTagType_IntId {
            get {
                return ((int)(this["ciTagType_IntId"]));
            }
            set {
                this["ciTagType_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int gridAnnBubbleType_IntId {
            get {
                return ((int)(this["gridAnnBubbleType_IntId"]));
            }
            set {
                this["gridAnnBubbleType_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int rebarTagType_Single_IntId {
            get {
                return ((int)(this["rebarTagType_Single_IntId"]));
            }
            set {
                this["rebarTagType_Single_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int rebarTagType_Arrows1_IntId {
            get {
                return ((int)(this["rebarTagType_Arrows1_IntId"]));
            }
            set {
                this["rebarTagType_Arrows1_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int rebarTagType_Arrows2_IntId {
            get {
                return ((int)(this["rebarTagType_Arrows2_IntId"]));
            }
            set {
                this["rebarTagType_Arrows2_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cropLine_IncludeLinks {
            get {
                return ((bool)(this["cropLine_IncludeLinks"]));
            }
            set {
                this["cropLine_IncludeLinks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool cropLine_ByViewBorders {
            get {
                return ((bool)(this["cropLine_ByViewBorders"]));
            }
            set {
                this["cropLine_ByViewBorders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cropLine_ByViewBorders_Top {
            get {
                return ((bool)(this["cropLine_ByViewBorders_Top"]));
            }
            set {
                this["cropLine_ByViewBorders_Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cropLine_ByViewBorders_Bottom {
            get {
                return ((bool)(this["cropLine_ByViewBorders_Bottom"]));
            }
            set {
                this["cropLine_ByViewBorders_Bottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cropLine_ByViewBorders_Left {
            get {
                return ((bool)(this["cropLine_ByViewBorders_Left"]));
            }
            set {
                this["cropLine_ByViewBorders_Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool cropLine_ByViewBorders_Right {
            get {
                return ((bool)(this["cropLine_ByViewBorders_Right"]));
            }
            set {
                this["cropLine_ByViewBorders_Right"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public double cropLine_a0 {
            get {
                return ((double)(this["cropLine_a0"]));
            }
            set {
                this["cropLine_a0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public double cropLine_a1 {
            get {
                return ((double)(this["cropLine_a1"]));
            }
            set {
                this["cropLine_a1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public double cropLine_a2 {
            get {
                return ((double)(this["cropLine_a2"]));
            }
            set {
                this["cropLine_a2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ciGroupTagType_IntId {
            get {
                return ((int)(this["ciGroupTagType_IntId"]));
            }
            set {
                this["ciGroupTagType_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int textNoteType_IntId {
            get {
                return ((int)(this["textNoteType_IntId"]));
            }
            set {
                this["textNoteType_IntId"] = value;
            }
        }
    }
}
