//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitOSA.WallReinforcer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.5.0.0")]
    public sealed partial class Docs : global::System.Configuration.ApplicationSettingsBase {
        
        private static Docs defaultInstance = ((Docs)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Docs())));
        
        public static Docs Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string user_Surname {
            get {
                return ((string)(this["user_Surname"]));
            }
            set {
                this["user_Surname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string structureTab_Switch_Position {
            get {
                return ((string)(this["structureTab_Switch_Position"]));
            }
            set {
                this["structureTab_Switch_Position"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TransferFile_Path {
            get {
                return ((string)(this["TransferFile_Path"]));
            }
            set {
                this["TransferFile_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int printSettings_ColorDepth {
            get {
                return ((int)(this["printSettings_ColorDepth"]));
            }
            set {
                this["printSettings_ColorDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int families_stuctClass_AddStandardParametersFor {
            get {
                return ((int)(this["families_stuctClass_AddStandardParametersFor"]));
            }
            set {
                this["families_stuctClass_AddStandardParametersFor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool families_stuctClass_DeterminateAuto {
            get {
                return ((bool)(this["families_stuctClass_DeterminateAuto"]));
            }
            set {
                this["families_stuctClass_DeterminateAuto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("02_Армирование_Стены и колонны")]
        public string reinf_Walls_WorksetName {
            get {
                return ((string)(this["reinf_Walls_WorksetName"]));
            }
            set {
                this["reinf_Walls_WorksetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("02_Армирование_Фундаменты_Выпуски")]
        public string reinf_FoundationAnchors_WorksetName {
            get {
                return ((string)(this["reinf_FoundationAnchors_WorksetName"]));
            }
            set {
                this["reinf_FoundationAnchors_WorksetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("02_Армирование_Плиты и балки_Выпуски")]
        public string reinf_SlabAnchors_WorksetName {
            get {
                return ((string)(this["reinf_SlabAnchors_WorksetName"]));
            }
            set {
                this["reinf_SlabAnchors_WorksetName"] = value;
            }
        }
    }
}
