//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitOSA.WallReinforcer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.5.0.0")]
    public sealed partial class ElementParametersAssistant : global::System.Configuration.ApplicationSettingsBase {
        
        private static ElementParametersAssistant defaultInstance = ((ElementParametersAssistant)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ElementParametersAssistant())));
        
        public static ElementParametersAssistant Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool p_Identity_Zone_AllowToSetValue {
            get {
                return ((bool)(this["p_Identity_Zone_AllowToSetValue"]));
            }
            set {
                this["p_Identity_Zone_AllowToSetValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool p_Identity_Section_AllowToSetValue {
            get {
                return ((bool)(this["p_Identity_Section_AllowToSetValue"]));
            }
            set {
                this["p_Identity_Section_AllowToSetValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool p_Mark_Construction_AllowToSetValue {
            get {
                return ((bool)(this["p_Mark_Construction_AllowToSetValue"]));
            }
            set {
                this["p_Mark_Construction_AllowToSetValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool p_Identity_Name_AllowToSetValue {
            get {
                return ((bool)(this["p_Identity_Name_AllowToSetValue"]));
            }
            set {
                this["p_Identity_Name_AllowToSetValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bip_Phases_PhaseCreated_AllowToSetValue {
            get {
                return ((bool)(this["bip_Phases_PhaseCreated_AllowToSetValue"]));
            }
            set {
                this["bip_Phases_PhaseCreated_AllowToSetValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bip_Identity_Workset_AllowToSetValue {
            get {
                return ((bool)(this["bip_Identity_Workset_AllowToSetValue"]));
            }
            set {
                this["bip_Identity_Workset_AllowToSetValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool p_Identity_MainElement_AllowToSetValue {
            get {
                return ((bool)(this["p_Identity_MainElement_AllowToSetValue"]));
            }
            set {
                this["p_Identity_MainElement_AllowToSetValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string p_Identity_Zone_DefaultValue {
            get {
                return ((string)(this["p_Identity_Zone_DefaultValue"]));
            }
            set {
                this["p_Identity_Zone_DefaultValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string p_Identity_Section_DefaultValue {
            get {
                return ((string)(this["p_Identity_Section_DefaultValue"]));
            }
            set {
                this["p_Identity_Section_DefaultValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string p_Mark_Construction_DefaultValue {
            get {
                return ((string)(this["p_Mark_Construction_DefaultValue"]));
            }
            set {
                this["p_Mark_Construction_DefaultValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string p_Identity_Name_DefaultValue {
            get {
                return ((string)(this["p_Identity_Name_DefaultValue"]));
            }
            set {
                this["p_Identity_Name_DefaultValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int bip_Phases_PhaseCreated_DefaultValue {
            get {
                return ((int)(this["bip_Phases_PhaseCreated_DefaultValue"]));
            }
            set {
                this["bip_Phases_PhaseCreated_DefaultValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int bip_Identity_Workset_DefaultValue {
            get {
                return ((int)(this["bip_Identity_Workset_DefaultValue"]));
            }
            set {
                this["bip_Identity_Workset_DefaultValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool p_Identity_MainElement_DefaultValue {
            get {
                return ((bool)(this["p_Identity_MainElement_DefaultValue"]));
            }
            set {
                this["p_Identity_MainElement_DefaultValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bip_Phases_PhaseCreated_EnableDefaultValue {
            get {
                return ((bool)(this["bip_Phases_PhaseCreated_EnableDefaultValue"]));
            }
            set {
                this["bip_Phases_PhaseCreated_EnableDefaultValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bip_Identity_Workset_EnableDefaultValue {
            get {
                return ((bool)(this["bip_Identity_Workset_EnableDefaultValue"]));
            }
            set {
                this["bip_Identity_Workset_EnableDefaultValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool p_Identity_MainElement_EnableDefaultValue {
            get {
                return ((bool)(this["p_Identity_MainElement_EnableDefaultValue"]));
            }
            set {
                this["p_Identity_MainElement_EnableDefaultValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool p_Identity_Name_EnableDefaultValue {
            get {
                return ((bool)(this["p_Identity_Name_EnableDefaultValue"]));
            }
            set {
                this["p_Identity_Name_EnableDefaultValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool p_Identity_Section_EnableDefaultValue {
            get {
                return ((bool)(this["p_Identity_Section_EnableDefaultValue"]));
            }
            set {
                this["p_Identity_Section_EnableDefaultValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool p_Identity_Zone_EnableDefaultValue {
            get {
                return ((bool)(this["p_Identity_Zone_EnableDefaultValue"]));
            }
            set {
                this["p_Identity_Zone_EnableDefaultValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool p_Mark_Construction_EnableDefaultValue {
            get {
                return ((bool)(this["p_Mark_Construction_EnableDefaultValue"]));
            }
            set {
                this["p_Mark_Construction_EnableDefaultValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingsForm_CallAfterEverySelection {
            get {
                return ((bool)(this["settingsForm_CallAfterEverySelection"]));
            }
            set {
                this["settingsForm_CallAfterEverySelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool pp_StandartItem_AllowToSetValue {
            get {
                return ((bool)(this["pp_StandartItem_AllowToSetValue"]));
            }
            set {
                this["pp_StandartItem_AllowToSetValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pp_StandartItem_EnableDefaultValue {
            get {
                return ((bool)(this["pp_StandartItem_EnableDefaultValue"]));
            }
            set {
                this["pp_StandartItem_EnableDefaultValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pp_StandartItem_DefaultValue {
            get {
                return ((bool)(this["pp_StandartItem_DefaultValue"]));
            }
            set {
                this["pp_StandartItem_DefaultValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Этаж 1")]
        public string p_Identity_Level_DefaultValue {
            get {
                return ((string)(this["p_Identity_Level_DefaultValue"]));
            }
            set {
                this["p_Identity_Level_DefaultValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool p_Identity_Level_EnableDefaultValue {
            get {
                return ((bool)(this["p_Identity_Level_EnableDefaultValue"]));
            }
            set {
                this["p_Identity_Level_EnableDefaultValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool p_Identity_Level_AllowToSetValue {
            get {
                return ((bool)(this["p_Identity_Level_AllowToSetValue"]));
            }
            set {
                this["p_Identity_Level_AllowToSetValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int pp_Number_OfLevel_DefaultValue {
            get {
                return ((int)(this["pp_Number_OfLevel_DefaultValue"]));
            }
            set {
                this["pp_Number_OfLevel_DefaultValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pp_Number_OfLevel_AllowToSetValue {
            get {
                return ((bool)(this["pp_Number_OfLevel_AllowToSetValue"]));
            }
            set {
                this["pp_Number_OfLevel_AllowToSetValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool pp_Number_OfLevel_EnableDefaultValue {
            get {
                return ((bool)(this["pp_Number_OfLevel_EnableDefaultValue"]));
            }
            set {
                this["pp_Number_OfLevel_EnableDefaultValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool p_Dims_Elevation_AllowToSetValue {
            get {
                return ((bool)(this["p_Dims_Elevation_AllowToSetValue"]));
            }
            set {
                this["p_Dims_Elevation_AllowToSetValue"] = value;
            }
        }
    }
}
