//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitOSA.WallReinforcer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.5.0.0")]
    public sealed partial class Modelling : global::System.Configuration.ApplicationSettingsBase {
        
        private static Modelling defaultInstance = ((Modelling)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Modelling())));
        
        public static Modelling Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int slabOpeningFamily_IntId {
            get {
                return ((int)(this["slabOpeningFamily_IntId"]));
            }
            set {
                this["slabOpeningFamily_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int wallOpeningFamily_IntId {
            get {
                return ((int)(this["wallOpeningFamily_IntId"]));
            }
            set {
                this["wallOpeningFamily_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int doorVoidFamily_IntId {
            get {
                return ((int)(this["doorVoidFamily_IntId"]));
            }
            set {
                this["doorVoidFamily_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int windowVoidFamily_IntId {
            get {
                return ((int)(this["windowVoidFamily_IntId"]));
            }
            set {
                this["windowVoidFamily_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int lintelElementCornerFamily_IntId {
            get {
                return ((int)(this["lintelElementCornerFamily_IntId"]));
            }
            set {
                this["lintelElementCornerFamily_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int lintelElementBarFamily_IntId {
            get {
                return ((int)(this["lintelElementBarFamily_IntId"]));
            }
            set {
                this["lintelElementBarFamily_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int lintelElementRebarFamily_IntId {
            get {
                return ((int)(this["lintelElementRebarFamily_IntId"]));
            }
            set {
                this["lintelElementRebarFamily_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int lintelFamily_IntId {
            get {
                return ((int)(this["lintelFamily_IntId"]));
            }
            set {
                this["lintelFamily_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool aiCreation_IncludeAttachedComponents {
            get {
                return ((bool)(this["aiCreation_IncludeAttachedComponents"]));
            }
            set {
                this["aiCreation_IncludeAttachedComponents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Отделка")]
        public string floorDecorType_BeginsWith {
            get {
                return ((string)(this["floorDecorType_BeginsWith"]));
            }
            set {
                this["floorDecorType_BeginsWith"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Отделка")]
        public string wallDecorType_BeginsWith {
            get {
                return ((string)(this["wallDecorType_BeginsWith"]));
            }
            set {
                this["wallDecorType_BeginsWith"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Отделка")]
        public string ceilingDecorType_BeginsWith {
            get {
                return ((string)(this["ceilingDecorType_BeginsWith"]));
            }
            set {
                this["ceilingDecorType_BeginsWith"] = value;
            }
        }
    }
}
