//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitOSA.WallReinforcer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.5.0.0")]
    public sealed partial class Reinforcement : global::System.Configuration.ApplicationSettingsBase {
        
        private static Reinforcement defaultInstance = ((Reinforcement)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Reinforcement())));
        
        public static Reinforcement Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string container_PartitionName {
            get {
                return ((string)(this["container_PartitionName"]));
            }
            set {
                this["container_PartitionName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string container_TypeName {
            get {
                return ((string)(this["container_TypeName"]));
            }
            set {
                this["container_TypeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool container_KeepSourceRebars {
            get {
                return ((bool)(this["container_KeepSourceRebars"]));
            }
            set {
                this["container_KeepSourceRebars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool reinf_Tranfer_Rebars {
            get {
                return ((bool)(this["reinf_Tranfer_Rebars"]));
            }
            set {
                this["reinf_Tranfer_Rebars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool reinf_Tranfer_RebarsInParts {
            get {
                return ((bool)(this["reinf_Tranfer_RebarsInParts"]));
            }
            set {
                this["reinf_Tranfer_RebarsInParts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool reinf_Tranfer_RebarContainers {
            get {
                return ((bool)(this["reinf_Tranfer_RebarContainers"]));
            }
            set {
                this["reinf_Tranfer_RebarContainers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool reinf_Tranfer_ARs {
            get {
                return ((bool)(this["reinf_Tranfer_ARs"]));
            }
            set {
                this["reinf_Tranfer_ARs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool reinf_Tranfer_AIs {
            get {
                return ((bool)(this["reinf_Tranfer_AIs"]));
            }
            set {
                this["reinf_Tranfer_AIs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool reinf_Tranfer_CIs {
            get {
                return ((bool)(this["reinf_Tranfer_CIs"]));
            }
            set {
                this["reinf_Tranfer_CIs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string container_Mark {
            get {
                return ((string)(this["container_Mark"]));
            }
            set {
                this["container_Mark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string container_Name {
            get {
                return ((string)(this["container_Name"]));
            }
            set {
                this["container_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double ci_Step {
            get {
                return ((double)(this["ci_Step"]));
            }
            set {
                this["ci_Step"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ci_Family_IntId {
            get {
                return ((int)(this["ci_Family_IntId"]));
            }
            set {
                this["ci_Family_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public double ci_SmallWallAccuracy {
            get {
                return ((double)(this["ci_SmallWallAccuracy"]));
            }
            set {
                this["ci_SmallWallAccuracy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double ci_ConcreteCatchAccuracy {
            get {
                return ((double)(this["ci_ConcreteCatchAccuracy"]));
            }
            set {
                this["ci_ConcreteCatchAccuracy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double ci_BottomAlign {
            get {
                return ((double)(this["ci_BottomAlign"]));
            }
            set {
                this["ci_BottomAlign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int reinf_Voids_X_Type_IntId {
            get {
                return ((int)(this["reinf_Voids_X_Type_IntId"]));
            }
            set {
                this["reinf_Voids_X_Type_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int reinf_Voids_Y_Type_IntId {
            get {
                return ((int)(this["reinf_Voids_Y_Type_IntId"]));
            }
            set {
                this["reinf_Voids_Y_Type_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double reinf_Voids_X_Step {
            get {
                return ((double)(this["reinf_Voids_X_Step"]));
            }
            set {
                this["reinf_Voids_X_Step"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double reinf_Voids_Y_Step {
            get {
                return ((double)(this["reinf_Voids_Y_Step"]));
            }
            set {
                this["reinf_Voids_Y_Step"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int reinf_Voids_X_N {
            get {
                return ((int)(this["reinf_Voids_X_N"]));
            }
            set {
                this["reinf_Voids_X_N"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int reinf_Voids_Y_N {
            get {
                return ((int)(this["reinf_Voids_Y_N"]));
            }
            set {
                this["reinf_Voids_Y_N"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A500")]
        public string reinf_RClass {
            get {
                return ((string)(this["reinf_RClass"]));
            }
            set {
                this["reinf_RClass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int reinf_Studs_Type_IntId {
            get {
                return ((int)(this["reinf_Studs_Type_IntId"]));
            }
            set {
                this["reinf_Studs_Type_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double reinf_Columns_Stirrup_Step {
            get {
                return ((double)(this["reinf_Columns_Stirrup_Step"]));
            }
            set {
                this["reinf_Columns_Stirrup_Step"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double reinf_Beams_Stirrup_Step {
            get {
                return ((double)(this["reinf_Beams_Stirrup_Step"]));
            }
            set {
                this["reinf_Beams_Stirrup_Step"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int reinf_Walls_X_Type_IntId {
            get {
                return ((int)(this["reinf_Walls_X_Type_IntId"]));
            }
            set {
                this["reinf_Walls_X_Type_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int reinf_Walls_Y_Type_IntId {
            get {
                return ((int)(this["reinf_Walls_Y_Type_IntId"]));
            }
            set {
                this["reinf_Walls_Y_Type_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int reinf_Columns_Stirrup_Type_IntId {
            get {
                return ((int)(this["reinf_Columns_Stirrup_Type_IntId"]));
            }
            set {
                this["reinf_Columns_Stirrup_Type_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int reinf_Beam_Stirrup_Type_IntId {
            get {
                return ((int)(this["reinf_Beam_Stirrup_Type_IntId"]));
            }
            set {
                this["reinf_Beam_Stirrup_Type_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double reinf_Walls_X_Bottom_CenterAlign {
            get {
                return ((double)(this["reinf_Walls_X_Bottom_CenterAlign"]));
            }
            set {
                this["reinf_Walls_X_Bottom_CenterAlign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public double reinf_RebarCover_Edge {
            get {
                return ((double)(this["reinf_RebarCover_Edge"]));
            }
            set {
                this["reinf_RebarCover_Edge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double reinf_Columns_Y_Edge_CenterAlign {
            get {
                return ((double)(this["reinf_Columns_Y_Edge_CenterAlign"]));
            }
            set {
                this["reinf_Columns_Y_Edge_CenterAlign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public double reinf_Studs_Step {
            get {
                return ((double)(this["reinf_Studs_Step"]));
            }
            set {
                this["reinf_Studs_Step"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public double reinf_Walls_X_Center_PreCenterAlign {
            get {
                return ((double)(this["reinf_Walls_X_Center_PreCenterAlign"]));
            }
            set {
                this["reinf_Walls_X_Center_PreCenterAlign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double reinf_Walls_Y_Edge_Step {
            get {
                return ((double)(this["reinf_Walls_Y_Edge_Step"]));
            }
            set {
                this["reinf_Walls_Y_Edge_Step"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public double reinf_Walls_Y_Edge_CenterAlign {
            get {
                return ((double)(this["reinf_Walls_Y_Edge_CenterAlign"]));
            }
            set {
                this["reinf_Walls_Y_Edge_CenterAlign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double reinf_Walls_Y_Step {
            get {
                return ((double)(this["reinf_Walls_Y_Step"]));
            }
            set {
                this["reinf_Walls_Y_Step"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double reinf_Walls_X_Step {
            get {
                return ((double)(this["reinf_Walls_X_Step"]));
            }
            set {
                this["reinf_Walls_X_Step"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int reinf_Columns_Y_Type_IntId {
            get {
                return ((int)(this["reinf_Columns_Y_Type_IntId"]));
            }
            set {
                this["reinf_Columns_Y_Type_IntId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int reinf_Columns_Y_N {
            get {
                return ((int)(this["reinf_Columns_Y_N"]));
            }
            set {
                this["reinf_Columns_Y_N"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double catchAccuracy {
            get {
                return ((double)(this["catchAccuracy"]));
            }
            set {
                this["catchAccuracy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int reinf_Shape_Stirrup_IntId {
            get {
                return ((int)(this["reinf_Shape_Stirrup_IntId"]));
            }
            set {
                this["reinf_Shape_Stirrup_IntId"] = value;
            }
        }
    }
}
