<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
    <Configurations>
      Debug 2025; 2025;
      Debug 2024; 2024;
      Debug 2023; 2023;
      Debug 2022; 2022;
      Debug 2021; 2021;
      Debug 2020; 2020;
    </Configurations>
  </PropertyGroup>

  <!-- RevitVersion -->
  <Choose>
    <When Condition="$(Configuration.Contains('2019'))">
      <PropertyGroup>
        <RevitVersion>2019</RevitVersion>
        <TargetFramework>net47</TargetFramework>
      </PropertyGroup>
    </When>
    <When Condition="$(Configuration.Contains('2020'))">
      <PropertyGroup>
        <RevitVersion>2020</RevitVersion>
        <TargetFramework>net47</TargetFramework>
      </PropertyGroup>
    </When>
    <When Condition="$(Configuration.Contains('2021'))">
      <PropertyGroup>
        <RevitVersion>2021</RevitVersion>
        <TargetFramework>net48</TargetFramework>
      </PropertyGroup>
    </When>
    <When Condition="$(Configuration.Contains('2022'))">
      <PropertyGroup>
        <RevitVersion>2022</RevitVersion>
        <TargetFramework>net48</TargetFramework>
      </PropertyGroup>
    </When>
    <When Condition="$(Configuration.Contains('2023'))">
      <PropertyGroup>
        <RevitVersion>2023</RevitVersion>
        <TargetFramework>net48</TargetFramework>
      </PropertyGroup>
    </When>
    <When Condition="$(Configuration.Contains('2024'))">
      <PropertyGroup>
        <RevitVersion>2024</RevitVersion>
        <TargetFramework>net48</TargetFramework>
      </PropertyGroup>
    </When>
    <When Condition="$(Configuration.Contains('2025'))">
      <PropertyGroup>
        <RevitVersion>2025</RevitVersion>
        <TargetFramework>net8.0-windows</TargetFramework>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup>
        <RevitVersion>2019</RevitVersion>
        <TargetFramework>net47</TargetFramework>
      </PropertyGroup>
    </Otherwise>
  </Choose>

	<Choose>
		<When Condition="$(Configuration.Contains('FP'))">
			<PropertyGroup>
				<Company>FP</Company>
			</PropertyGroup>
		</When>
		<When Condition="$(Configuration.Contains('OLP'))">
			<PropertyGroup>
				<Company>OLP</Company>
			</PropertyGroup>
		</When>
		<Otherwise>
			<PropertyGroup>
				<Company>FP</Company>
			</PropertyGroup>
		</Otherwise>
	</Choose>

	<!-- Net Core -->
  <PropertyGroup Condition="!$(TargetFramework.StartsWith('net4'))">
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

  <!-- Release -->
  <PropertyGroup Condition="!$(Configuration.Contains('Debug'))">
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\$(RevitVersion)</OutputPath>
    <DefineConstants>$(DefineConstants);REVIT$(RevitVersion);COMPANY_$(Company)</DefineConstants>
    <NoWarn>MSB3052</NoWarn>
    <DebugType>None</DebugType>
  </PropertyGroup>

  <!-- Debug -->
  <PropertyGroup Condition="$(Configuration.Contains('Debug'))">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>$(DefineConstants);DEBUG;TRACE;REVIT$(RevitVersion);COMPANY_$(Company)</DefineConstants>
    <DebugType>Full</DebugType>
  </PropertyGroup>

  <!-- DebugRevitVersion -->
  <PropertyGroup Condition="$(Configuration.Contains('Debug'))">
    <DebugRevitVersion>$(RevitVersion)</DebugRevitVersion>
    <StartAction>Program</StartAction>
    <StartProgram>C:\Program Files\Autodesk\Revit $(DebugRevitVersion)\Revit.exe</StartProgram>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId></PackageId>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <PropertyGroup>
    <PackageAssemblyVersion></PackageAssemblyVersion>
  </PropertyGroup>
  <PropertyGroup Condition="$(Configuration.Contains('Debug'))">
    <IncludePackageReferencesDuringMarkupCompilation>false</IncludePackageReferencesDuringMarkupCompilation>
    <Revision>$([MSBuild]::Divide($([System.DateTime]::Now.TimeOfDay.TotalSeconds), 4).ToString('F0'))</Revision>
    <PackageAssemblyVersion>.Dev.$(Version).$(Revision)</PackageAssemblyVersion>
  </PropertyGroup>

  <PropertyGroup>
    <Company>FP</Company>
    <Authors>Pavel Smirnov</Authors>
    <Description>Плагин для армирования конструкций 3D </Description>
    <CopyrightYears>$([System.DateTime]::Now.ToString('yyyy'))</CopyrightYears>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyName></AssemblyName>
    <Product>$(PackageId)</Product>
    <Copyright>Copyright © $(CopyrightYears) $(Company)</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Revit\App.cs" />
  </ItemGroup>

  <!-- Fody -->
  <PropertyGroup>
    <WeaverConfiguration>
      <Weavers>
        <PropertyChanged />
      </Weavers>
    </WeaverConfiguration>
    <RootNamespace>RevitOSA.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MahApps.Metro" Version="2.4.11" />
    <PackageReference Include="Prism.Core" Version="8.1.97" />
    <PackageReference Include="Revit.Async" Version="2.1.1" />
    <PackageReference Include="Revit_All_Main_Versions_API_x64" Version="$(RevitVersion).*" IncludeAssets="build; compile" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Annotations.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Annotations.settings</DependentUpon>
    </Compile>
    <Compile Update="Properties\Docs.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Docs.settings</DependentUpon>
    </Compile>
    <Compile Update="Properties\ElementParametersAssistant.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>ElementParametersAssistant.settings</DependentUpon>
    </Compile>
    <Compile Update="Properties\Modelling.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Modelling.settings</DependentUpon>
    </Compile>
    <Compile Update="Properties\Reinforcement.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Reinforcement.settings</DependentUpon>
    </Compile>
    <Compile Update="Resources1P\ElemMarkDescriptions.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ElemMarkDescriptions.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources1P\ElemZoneToSheetSet.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ElemZoneToSheetSet.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources1P\FamilyNamePrefixes.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>FamilyNamePrefixes.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources1P\IdenityZones.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>IdenityZones.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources1P\LinePatterns.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LinePatterns.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources1P\ReinforcementPartitionNames.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ReinforcementPartitionNames.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources1P\RevitParameters.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>RevitParameters.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources1P\ElemMarkDescriptions.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ElemMarkDescriptions.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources1P\ElemZoneToSheetSet.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ElemZoneToSheetSet.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources1P\FamilyNamePrefixes.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>FamilyNamePrefixes.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources1P\IdenityZones.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>IdenityZones.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources1P\LinePatterns.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>LinePatterns.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources1P\ReinforcementPartitionNames.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ReinforcementPartitionNames.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources1P\RevitParameters.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>RevitParameters.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\" />
    <Folder Include="ViewModels\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Annotations.settings">
      <Generator>PublicSettingsSingleFileGenerator</Generator>
      <LastGenOutput>Annotations.Designer.cs</LastGenOutput>
    </None>
    <None Update="Properties\Docs.settings">
      <Generator>PublicSettingsSingleFileGenerator</Generator>
      <LastGenOutput>Docs.Designer.cs</LastGenOutput>
    </None>
    <None Update="Properties\ElementParametersAssistant.settings">
      <Generator>PublicSettingsSingleFileGenerator</Generator>
      <LastGenOutput>ElementParametersAssistant.Designer.cs</LastGenOutput>
    </None>
    <None Update="Properties\Modelling.settings">
      <Generator>PublicSettingsSingleFileGenerator</Generator>
      <LastGenOutput>Modelling.Designer.cs</LastGenOutput>
    </None>
    <None Update="Properties\Reinforcement.settings">
      <Generator>PublicSettingsSingleFileGenerator</Generator>
      <LastGenOutput>Reinforcement.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>